#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

app_cgv:
  path: /cgv
  controller: App\Controller\ContentController::cgv
  defaults:
 

# page Mention légale

app_MentionLegale:
  path: /MentionLegale
  controller: App\Controller\ContentController::mention
  defaults:
    

#page Politique Confidentialité
app_PolitiqueConfi:
  path: /PolitiqueConfi
  controller: App\Controller\ContentController::politique
  defaults:
  

  